services:
  cv-pipeline:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "C:/food-pipeline-models/yolov8n_food_best.pt:/app/models/yolov8n_food_best.pt"
      - "C:/food-pipeline-models/efficientnet_b0_food101_best.pt:/app/models/efficientnet_b0_food101_best.pt"
      - "C:/food-pipeline-models/idx_to_class.json:/app/models/idx_to_class.json"
      - "C:/food-pipeline-models/usda.index:/app/nutrition/usda.index"
      - "C:/food-pipeline-models/usda_records.json:/app/nutrition/usda_records.json"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - food-net
    restart: unless-stopped

  gradio-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - API_URL=http://cv-pipeline:8000/analyze
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - PYTHONUNBUFFERED=1
    networks:
      - food-net
    depends_on:
      - cv-pipeline
    restart: unless-stopped

networks:
  food-net:
    driver: bridge